### ISSUE TITLE
Library Name

### ISSUE THREAD

**Issue by back2dos** [haxetink/tink_validation#1]
@kevinresol I've thrown around your question in my mind on how this library should be called. My thinking is that it has actually less to do with anonymous objects and more with validation in general, so I guess that's what the name should express, e.g. `tink_validation` (or `tink_validate` or `tink_validator`, depending on what you want to call the facade class). Any thoughts on that?

**Comment by kevinresol** [comment]
Yes, validation is the core of this library. I don't have much preference about the noun/verb form though. Maybe we just make it `tink_validation` with a class `Validation`?

p.s. In my thought this library should provide mainly two functions, one is `extract` or `copy`, that would validate and then copy the required fields from the original object and should throw when the object does not conform to the required Type. Another one is `validate`, that is same as `copy` but it does only the validation and return nothing.

**Comment by back2dos** [comment]
Oh, hmm, interesting! This separation got me thinking. What about splitting it into two libraries, one for type based deep copying (which will probably beat the reflection based alternative by lengths) and one for in-place-validation? Then "extracting" comes down to first checking and then copying. It can can still be a comfort feature of the validation, my point here is rather that copying (without the type checks) can be useful on its own, because of its performance.

**Comment by kevinresol** [comment]
Then what about `tink_clone` and `tink_validation`?

tink_clone:
- `copy()`: just deep copy without validation

tink_validation:
- `validate()`: just validate
- `extract()/copy()`: copy with validation

**Comment by back2dos** [comment]
Sounds good to me ;)

**Comment by kevinresol** [comment]
Good, for now I will just change the github repo name. I will see if I have time early next week to touch the codes.

**Comment by back2dos** [comment]
Sure. Let me know if you need any help ;)

**Comment by back2dos** [comment]
This seems dealt with.
