### ISSUE TITLE
Extract from multiple objects

### ISSUE THREAD

**Issue by kevinresol** [haxetink/tink_validation#2]
I am looking for a functionality that values can be extracted from more than one candidate objects.

Example:

``` haxe
var obj1:Dynamic = {a:1}
var obj2:Dynamic = {b:2}
var obj3:Dynamic = {c:3}

var result:{a:Int, b:Int, ?d:Int} = Validation.merge([obj1, obj2, obj3]);
```

Then the validator will, for each field, loop through the candidate objects and use the first one that has the required field. So that in the above example, the result will be `{a:1, b:2, d:null}`

We have a few questions here:
1. Things may get complicated when there are nested objects
2. Not sure if there will be performance issue, because we need to loop the objects for _each field_

@back2dos looking for help from your sixth-sense

**Comment by back2dos** [comment]
Phew. This is actually really interesting, especially when nesting comes into play with collections, e.g.:

``` haxe
var o:{ 
   foo:Array<{
      bar:Int, 
      boink:String 
   }>
} = Validation.merge(
  { foo: [{ bar: 1 }, { bar: 2 }] }, 
  { foo: [{ boink: "blub" }] }
)` 
```

In that case you will either need to reduce the resulting array's length to the minimum, or make the fields of all elements optional.

Intuitively, I would say you have found yourself a really tricky problem here my friend. It may be wise to simplify it by putting a few limitations in place for a first version. Do you have a real-world-ish use case to use as a baseline?

**Comment by kevinresol** [comment]
Use case? Yes, ufront. Which merges parameters from cookies, query and post.

Here I'm inclined to implement "stop further scan as soon as you find the field and fail if that field does not conform".
So in your example it should fail with "the field boink doesn't exist"

What do you think?

**Comment by back2dos** [comment]
If I may digress: It's not my place to tell other how to write their web apps, but I feel I should point out that merging query, body and cookie params opens the door for certain types of XSS attacks and goes against REST.

But back to the question: for ufront it would seem like the source is a MultiValueMap or something, right? And you can't really have very deep nesting? Is it of any use to solve just that problem?

Well, I guess there's a number of ways to go about it. As a quick solution, I suggest merging the objects by means of reflection and then `extract` the required values from that.

I will need some time to figure out a good way to make it directly with macros, but if you have any concrete ideas I might be able to help you pursue them ;)

**Comment by kevinresol** [comment]
Yes it is MultiValueMap right now and I found that very limiting. Detailed explanation can be found here: https://github.com/ufront/ufront-mvc/issues/48#issuecomment-209474016. By storing the parameters in object instead, they can be better handled.

For web parameters merging, I think I agree it is not a good idea, besides security problem it also bring ambiguity to user code (i.e. you won't know from where you are getting a parameter). But I am not sure if I can get rid of it right now, because that would be a major breaking change. So what I can do right now is to replace MultiValueMap, so that it can handle more complex data first. Only after that I will consider removing the merging altogether.

**Comment by back2dos** [comment]
I guess it's time to close this, as the original use case is handled by tink_anon. We can explore more complex cases there, if they come up.
