### ISSUE TITLE
'Cannot use Void as a value' when validating 

### ISSUE THREAD

**Issue by JbIPS** [haxetink/tink_validation#6]
It looks like I missed something with #5 because this snippet 
```haxe
     var source: Dynamic = {a: 1, test: ['a']};
     try {
       Validation.validate((source: {a: Int, test: Array<String>}));
       trace('OK');
     } catch(e: Dynamic) {
       trace('Boom', e);
     }
```
gives me a compilation error:
```
GenValidator.hx:66: characters 4-19 : Cannot use Void as value
```

From the [position of the error](https://github.com/haxetink/tink_validation/blob/master/src/tink/validation/macro/GenValidator.hx#L66) and the test sample I can tell the `Array` is the problem but I can't tell the difference with the other test samples.

Any ideas or leads? Thanks

**Comment by kevinresol** [comment]
This looks like some missing `return`

**Comment by JbIPS** [comment]
> I can't tell the difference with the other test samples.

Correction, I think the array type is the trigger: all tests are using anon array and this sample use a primitive type (I can reproduce with an `Array<Int>`)

**Comment by JbIPS** [comment]
> This looks like some missing return

A missing return in the macro? I'm not sure. Could `$e` be `Void` when the `Array` is containing `String`? I found this error in the [manual](http://code.haxe.org/category/principles/everything-is-an-expression.html) but I can't relate to this problem :/

**Comment by kevinresol** [comment]
Well because the validation statement does not return a value 
https://github.com/haxetink/tink_validation/blob/master/src/tink/validation/macro/GenValidator.hx#L26

**Comment by JbIPS** [comment]
![Snap](https://media.giphy.com/media/3o6ozC2VM9R0XSMNKo/giphy.gif)

That's why it worked with the extractor! Should we return the value or null?

**Comment by kevinresol** [comment]
Nope, validator is not supposed to return value at all. Basically you shouldn't assign the expr to a variable. That should fix it.

**Comment by JbIPS** [comment]
I see your point but the assignment is here so we could pop the path array and then return the expr to array creation. Do you have another method to achieve that (I'm reaching my macro knowledge limit)?

**Comment by kevinresol** [comment]
No problem. I'll try to have a look soon. (In a day or two)

**Comment by JbIPS** [comment]
Thank you, I'll keep searching and tell you if I find something interesting!

**Comment by kevinresol** [comment]
No problem. I'll try to have a look soon. (In a day or two)

**Comment by back2dos** [comment]
Pretty sure if you just remove the comprehension [here](https://github.com/haxetink/tink_validation/blob/13a2f58cb03ceff12e2c8a43e3f948718e9cb1ee/src/tink/validation/macro/GenValidator.hx#L63) it will work, so it should read:

```haxe
			for(i in 0...(value:Array<Dynamic>).length) {
				var value = (value:Array<Dynamic>)[i];
				path.push(Std.string(i));
				$e;
				path.pop();
			};
```

**Comment by JbIPS** [comment]
You were faster than me! I'm writing the PR right now ;)

**Comment by kevinresol** [comment]
> Pretty sure if you just remove the comprehension here it will work, so it should read:

Yeah that's what I have in mind, but was on a phone and too hard to type code there

**Comment by JbIPS** [comment]
It sure is, but thank you for pointing me in the right way
